plugins {
    id "com.gradleup.shadow" version "${shadowJar}"
    id("io.papermc.paperweight.userdev") version "${gradlePaperweight}"
    id "java"
}

group = "com.spectrasonic"
version = "${pluginversion}"

repositories {
    mavenCentral()
    gradlePluginPortal()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }

    maven { url = "https://maven.devs.beer/" }

    maven { url = "https://repo.aikar.co/content/groups/aikar/" }
}

dependencies {
    // compileOnly("io.papermc.paper:paper-api:${paperversion}-R0.1-SNAPSHOT") // Paper
    paperweight.paperDevBundle("${paperversion}-R0.1-SNAPSHOT")

    // Lombok
    compileOnly "org.projectlombok:lombok:${lombok}"
    annotationProcessor("org.projectlombok:lombok:${lombok}")

    // Minimessage - Adventure
    implementation "net.kyori:adventure-text-minimessage:${minimessage}"
    implementation "net.kyori:adventure-api:${minimessage}"

    // ItemsAdder
    compileOnly "dev.lone:api-itemsadder:${itemsAdder}"

    implementation "co.aikar:acf-paper:${acfaikar}"

}


shadowJar {
    relocate "co.aikar.commands", "com.spectrasonic.PoppyGrabPacks.acf"
    relocate "co.aikar.locales", "com.spectrasonic.PoppyGrabPacks.locales"
    destinationDirectory = file("${rootDir}/out")
    archiveFileName = "${rootProject.name}-${version}.jar"
}


build.dependsOn shadowJar
build.finalizedBy reobfJar

def targetJavaVersion = "${javaversion}"
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset = "UTF-8"
    filesMatching("plugin.yml") {
        expand props
    }
}